server.port=8080

spring.datasource.url=jdbc:snowflake://hjdlbku-cv00477.snowflakecomputing.com/?db=SPRING_SNOWFLAKE_DB&schema=PUBLIC&warehouse=TINY_WAREHOUSE&role=TERRAFORM_ROLE
spring.datasource.username=terraform_user
spring.datasource.password=TerraformSnowflake2026!
spring.datasource.driver-class-name=net.snowflake.client.jdbc.SnowflakeDriver

spring.datasource.hikari.maximumPoolSize=2
spring.datasource.hikari.connectionTimeout=30000
